// Momente A1 — barcha darslardan so'zlar (24 dars, 1200+ so'z)
// Manba: Momente A1 darsligi, O'zbek tiliga tarjima bilan

export type WordType = 'noun' | 'verb' | 'adjective' | 'adverb' | 'phrase' | 'other';
export type Article = 'der' | 'die' | 'das' | null;

export interface Word {
  id: number;
  lesson: number;
  de: string;
  uz: string;
  type: WordType;
  article?: Article;
  example?: string;
}

export const WORDS: Word[] = [
  // ─── LEKTION 1: Wie heißt du? ───────────────────────────────────────────
  { id: 1, lesson: 1, de: 'Wie heißt du?', uz: 'Isming nima?', type: 'phrase' },
  { id: 2, lesson: 1, de: 'Hallo', uz: 'Salom', type: 'other' },
  { id: 3, lesson: 1, de: 'Tschüs', uz: 'Xayr', type: 'other' },
  { id: 4, lesson: 1, de: 'Auf Wiedersehen', uz: "Ko'rishguncha", type: 'other' },
  { id: 5, lesson: 1, de: 'Danke', uz: 'Rahmat', type: 'other' },
  { id: 6, lesson: 1, de: 'Entschuldigung', uz: 'Kechirasiz', type: 'other' },
  { id: 7, lesson: 1, de: 'Bitte', uz: 'Iltimos', type: 'other' },
  { id: 8, lesson: 1, de: 'Wie bitte?', uz: 'Nima dedingiz?', type: 'phrase' },
  { id: 9, lesson: 1, de: 'ich bin', uz: 'men ... man', type: 'phrase' },
  { id: 10, lesson: 1, de: 'du bist', uz: 'sen ... san', type: 'phrase' },
  { id: 11, lesson: 1, de: 'Der Name', uz: 'Ism', type: 'noun', article: 'der' },
  { id: 12, lesson: 1, de: 'Der Vorname', uz: 'Familiya', type: 'noun', article: 'der' },
  { id: 13, lesson: 1, de: 'Mein Name ist', uz: 'Mening ismim ...', type: 'phrase' },
  { id: 14, lesson: 1, de: 'Woher kommst du?', uz: 'Qayerliksan?', type: 'phrase' },
  { id: 15, lesson: 1, de: 'Das Alphabet', uz: 'Alifbo', type: 'noun', article: 'das' },
  { id: 16, lesson: 1, de: 'Die Musik', uz: 'Musiqa', type: 'noun', article: 'die' },
  { id: 17, lesson: 1, de: 'Das Land', uz: 'Mamlakat', type: 'noun', article: 'das' },
  { id: 18, lesson: 1, de: 'Die Information', uz: "Ma'lumot", type: 'noun', article: 'die' },
  { id: 19, lesson: 1, de: 'lernen', uz: "O'rganmoq", type: 'verb' },
  { id: 20, lesson: 1, de: 'kommen', uz: 'Kelmoq', type: 'verb' },
  { id: 21, lesson: 1, de: 'wie geht\'s dir?', uz: 'Axvollaring qalay?', type: 'phrase' },
  { id: 22, lesson: 1, de: 'sehr gut', uz: 'Juda yaxshi', type: 'phrase' },
  { id: 23, lesson: 1, de: 'es geht', uz: 'Ketyapti', type: 'phrase' },
  { id: 24, lesson: 1, de: 'nicht so gut', uz: 'Yaxshi emas', type: 'phrase' },
  { id: 25, lesson: 1, de: 'super', uz: 'Ajoyib', type: 'adjective' },
  { id: 26, lesson: 1, de: 'Wer sind Sie?', uz: 'Kimsiz?', type: 'phrase' },
  { id: 27, lesson: 1, de: 'Die Schweiz', uz: 'Shveysariya', type: 'noun', article: 'die' },
  { id: 28, lesson: 1, de: 'Das Gespräch', uz: 'Suhbat', type: 'noun', article: 'das' },
  { id: 29, lesson: 1, de: 'Der Herr', uz: 'Janob', type: 'noun', article: 'der' },
  { id: 30, lesson: 1, de: 'Die Frau', uz: 'Xonim', type: 'noun', article: 'die' },

  // ─── LEKTION 2: Jahre alt ───────────────────────────────────────────────
  { id: 31, lesson: 2, de: 'Das Jahr', uz: 'Yil', type: 'noun', article: 'das' },
  { id: 32, lesson: 2, de: 'verheiratet', uz: 'Turmush qurgan', type: 'adjective' },
  { id: 33, lesson: 2, de: 'Das Kind', uz: 'Bola', type: 'noun', article: 'das' },
  { id: 34, lesson: 2, de: 'wohnen', uz: 'Yashamoq', type: 'verb' },
  { id: 35, lesson: 2, de: 'Der Beruf', uz: 'Kasb', type: 'noun', article: 'der' },
  { id: 36, lesson: 2, de: 'studieren', uz: 'Tahsil olmoq', type: 'verb' },
  { id: 37, lesson: 2, de: 'arbeiten', uz: 'Ishlamoq', type: 'verb' },
  { id: 38, lesson: 2, de: 'Die Firma', uz: 'Korxona', type: 'noun', article: 'die' },
  { id: 39, lesson: 2, de: 'Der Schüler', uz: "O'quvchi", type: 'noun', article: 'der' },
  { id: 40, lesson: 2, de: 'Der Rentner', uz: "Nafaqaxo'r", type: 'noun', article: 'der' },
  { id: 41, lesson: 2, de: 'Die Krankenschwester', uz: 'Xamshira', type: 'noun', article: 'die' },
  { id: 42, lesson: 2, de: 'Der Tierarzt', uz: 'Veterinar', type: 'noun', article: 'der' },
  { id: 43, lesson: 2, de: 'Der Schauspieler', uz: 'Aktyor', type: 'noun', article: 'der' },
  { id: 44, lesson: 2, de: 'Der Sänger', uz: "Qo'shiqchi", type: 'noun', article: 'der' },
  { id: 45, lesson: 2, de: 'Das Praktikum', uz: 'Amaliyot', type: 'noun', article: 'das' },
  { id: 46, lesson: 2, de: 'Der Familienstand', uz: 'Oilaviy ahvoli', type: 'noun', article: 'der' },
  { id: 47, lesson: 2, de: 'gechieden sein', uz: 'Ajrashgan', type: 'phrase' },
  { id: 48, lesson: 2, de: 'Der Single', uz: 'Boydoq', type: 'noun', article: 'der' },
  { id: 49, lesson: 2, de: 'Allein', uz: "Yolg'iz", type: 'adverb' },
  { id: 50, lesson: 2, de: 'zusammenleben', uz: 'Birga yashamoq', type: 'verb' },

  // ─── LEKTION 3: Die Familie ──────────────────────────────────────────────
  { id: 51, lesson: 3, de: 'Die Familie', uz: 'Oila', type: 'noun', article: 'die' },
  { id: 52, lesson: 3, de: 'Die Mutter', uz: 'Ona', type: 'noun', article: 'die' },
  { id: 53, lesson: 3, de: 'Der Vater', uz: 'Ota', type: 'noun', article: 'der' },
  { id: 54, lesson: 3, de: 'Die Schwester', uz: 'Opa', type: 'noun', article: 'die' },
  { id: 55, lesson: 3, de: 'Der Onkel', uz: "Amaki, tog'a", type: 'noun', article: 'der' },
  { id: 56, lesson: 3, de: 'Die Oma', uz: 'Buvi', type: 'noun', article: 'die' },
  { id: 57, lesson: 3, de: 'Das Enkelkind', uz: 'Nabira', type: 'noun', article: 'das' },
  { id: 58, lesson: 3, de: 'Die Tante', uz: 'Xola', type: 'noun', article: 'die' },
  { id: 59, lesson: 3, de: 'Der Mann', uz: 'Erkak', type: 'noun', article: 'der' },
  { id: 60, lesson: 3, de: 'sprechen', uz: 'Gapirmoq', type: 'verb' },
  { id: 61, lesson: 3, de: 'Das Fest', uz: 'Bayram', type: 'noun', article: 'das' },
  { id: 62, lesson: 3, de: 'planen', uz: 'Rejalashtirmoq', type: 'verb' },
  { id: 63, lesson: 3, de: 'Die Sprache', uz: 'Til', type: 'noun', article: 'die' },
  { id: 64, lesson: 3, de: 'ein bisschen', uz: 'Biroz', type: 'adverb' },
  { id: 65, lesson: 3, de: 'gar nicht', uz: 'Umuman', type: 'adverb' },
  { id: 66, lesson: 3, de: 'interessant', uz: 'Qiziqarli', type: 'adjective' },
  { id: 67, lesson: 3, de: 'Die Visitenkarte', uz: "Tashrif qog'ozi", type: 'noun', article: 'die' },
  { id: 68, lesson: 3, de: 'glauben', uz: 'Ishonmoq', type: 'verb' },
  { id: 69, lesson: 3, de: 'Polen', uz: 'Polsha', type: 'noun', article: null },
  { id: 70, lesson: 3, de: 'Das Mitglied', uz: "A'zo", type: 'noun', article: 'das' },

  // ─── LEKTION 4: Zu Hause ────────────────────────────────────────────────
  { id: 71, lesson: 4, de: 'Das Möbel', uz: 'Mebel', type: 'noun', article: 'das' },
  { id: 72, lesson: 4, de: 'Das Bild', uz: 'Rasm', type: 'noun', article: 'das' },
  { id: 73, lesson: 4, de: 'schön', uz: 'Chiroyli', type: 'adjective' },
  { id: 74, lesson: 4, de: 'teuer', uz: 'Qimmat', type: 'adjective' },
  { id: 75, lesson: 4, de: 'hässlich', uz: 'Xunuk', type: 'adjective' },
  { id: 76, lesson: 4, de: 'günstig', uz: 'Arzon', type: 'adjective' },
  { id: 77, lesson: 4, de: 'Der Stuhl', uz: 'Stol', type: 'noun', article: 'der' },
  { id: 78, lesson: 4, de: 'Der Spiegel', uz: 'Oyna', type: 'noun', article: 'der' },
  { id: 79, lesson: 4, de: 'Das Zimmer', uz: 'Xona', type: 'noun', article: 'das' },
  { id: 80, lesson: 4, de: 'modern', uz: 'Zamonaviy', type: 'adjective' },
  { id: 81, lesson: 4, de: 'praktisch', uz: 'Qulay', type: 'adjective' },
  { id: 82, lesson: 4, de: 'klein', uz: 'Kichkina', type: 'adjective' },
  { id: 83, lesson: 4, de: 'Das Hotel', uz: 'Mehmonxona', type: 'noun', article: 'das' },
  { id: 84, lesson: 4, de: 'groß', uz: 'Katta', type: 'adjective' },
  { id: 85, lesson: 4, de: 'Wie viel kostet?', uz: 'Qancha turadi?', type: 'phrase' },
  { id: 86, lesson: 4, de: 'Der Euro', uz: 'Yevro', type: 'noun', article: 'der' },
  { id: 87, lesson: 4, de: 'Der Preis', uz: 'Narx', type: 'noun', article: 'der' },
  { id: 88, lesson: 4, de: 'Das Sonderangebot', uz: 'Maxsus taklif', type: 'noun', article: 'das' },
  { id: 89, lesson: 4, de: 'Das Geschäft', uz: "Do'kon", type: 'noun', article: 'das' },
  { id: 90, lesson: 4, de: 'wirklich', uz: 'Haqiqatdan', type: 'adverb' },

  // ─── LEKTION 5: Das Ding ────────────────────────────────────────────────
  { id: 91, lesson: 5, de: 'Die Uhr', uz: 'Soat', type: 'noun', article: 'die' },
  { id: 92, lesson: 5, de: 'Das Auto', uz: 'Avtomobil', type: 'noun', article: 'das' },
  { id: 93, lesson: 5, de: 'Das Handy', uz: 'Telefon', type: 'noun', article: 'das' },
  { id: 94, lesson: 5, de: 'Das Buch', uz: 'Kitob', type: 'noun', article: 'das' },
  { id: 95, lesson: 5, de: 'Die Farbe', uz: 'Rang', type: 'noun', article: 'die' },
  { id: 96, lesson: 5, de: 'schreiben', uz: 'Yozmoq', type: 'verb' },
  { id: 97, lesson: 5, de: 'Das Wörterbuch', uz: "Lug'at", type: 'noun', article: 'das' },
  { id: 98, lesson: 5, de: 'Die Jacke', uz: 'Kurtka', type: 'noun', article: 'die' },
  { id: 99, lesson: 5, de: 'Die Seife', uz: 'Sovun', type: 'noun', article: 'die' },
  { id: 100, lesson: 5, de: 'Das Handtuch', uz: "Ro'molcha", type: 'noun', article: 'das' },
  { id: 101, lesson: 5, de: 'Der Föhn', uz: 'Fen', type: 'noun', article: 'der' },
  { id: 102, lesson: 5, de: 'bestellen', uz: 'Buyurtma qilmoq', type: 'verb' },
  { id: 103, lesson: 5, de: 'Die Sonnenbrille', uz: 'Quyoshdan himoyalovchi ko\'zoynak', type: 'noun', article: 'die' },
  { id: 104, lesson: 5, de: 'noch einmal', uz: 'Yana bir marta', type: 'phrase' },
  { id: 105, lesson: 5, de: 'Das Feuerzeug', uz: 'Olov yondirgich', type: 'noun', article: 'das' },
  { id: 106, lesson: 5, de: 'Der Geldbeutel', uz: 'Hamyon', type: 'noun', article: 'der' },
  { id: 107, lesson: 5, de: 'Das Taschentuch', uz: 'Salfetka', type: 'noun', article: 'das' },
  { id: 108, lesson: 5, de: 'sagen', uz: 'Aytmoq', type: 'verb' },
  { id: 109, lesson: 5, de: 'fragen', uz: 'Soramoq', type: 'verb' },
  { id: 110, lesson: 5, de: 'antworten', uz: 'Javob bermoq', type: 'verb' },

  // ─── LEKTION 6: Oh Gott! ────────────────────────────────────────────────
  { id: 111, lesson: 6, de: 'Die Arbeit', uz: 'Ish', type: 'noun', article: 'die' },
  { id: 112, lesson: 6, de: 'Das Passwort', uz: 'Parol', type: 'noun', article: 'das' },
  { id: 113, lesson: 6, de: 'Das WLAN', uz: 'Wi-fi', type: 'noun', article: 'das' },
  { id: 114, lesson: 6, de: 'brauchen', uz: 'Kerak bo\'lmoq', type: 'verb' },
  { id: 115, lesson: 6, de: 'Das Büro', uz: 'Byuro', type: 'noun', article: 'das' },
  { id: 116, lesson: 6, de: 'morgen', uz: 'Ertaga', type: 'adverb' },
  { id: 117, lesson: 6, de: 'leider', uz: 'Afsuski', type: 'adverb' },
  { id: 118, lesson: 6, de: 'keine Zeit haben', uz: "Vaqti yo'q bo'lmoq", type: 'phrase' },
  { id: 119, lesson: 6, de: 'Die Zeit', uz: 'Vaqt', type: 'noun', article: 'die' },
  { id: 120, lesson: 6, de: 'Der Termin', uz: 'Uchrashuv', type: 'noun', article: 'der' },
  { id: 121, lesson: 6, de: 'Der Schreibtisch', uz: 'Yozuv stoli', type: 'noun', article: 'der' },
  { id: 122, lesson: 6, de: 'auf Wiederhören', uz: 'Qayta gaplashguncha', type: 'phrase' },
  { id: 123, lesson: 6, de: 'Der Bürokaufmann', uz: 'Ofis xodimi', type: 'noun', article: 'der' },
  { id: 124, lesson: 6, de: 'telefonieren', uz: 'Telefonlashmoq', type: 'verb' },
  { id: 125, lesson: 6, de: 'viele Grüße', uz: 'Iliq salomlar', type: 'phrase' },

  // ─── LEKTION 7: Hobbys ──────────────────────────────────────────────────
  { id: 126, lesson: 7, de: 'können', uz: 'Qila olmoq', type: 'verb' },
  { id: 127, lesson: 7, de: 'tanzen', uz: 'Raqsga tushmoq', type: 'verb' },
  { id: 128, lesson: 7, de: 'das Hobby', uz: 'Hobbi', type: 'noun', article: 'das' },
  { id: 129, lesson: 7, de: 'oft', uz: 'Tez-tez', type: 'adverb' },
  { id: 130, lesson: 7, de: 'manchmal', uz: "Ba'zan", type: 'adverb' },
  { id: 131, lesson: 7, de: 'nie', uz: 'Hech qachon', type: 'adverb' },
  { id: 132, lesson: 7, de: 'lesen', uz: "O'qimoq", type: 'verb' },
  { id: 133, lesson: 7, de: 'Die Freizeit', uz: "Bo'sh vaqt", type: 'noun', article: 'die' },
  { id: 134, lesson: 7, de: 'Das Konzert', uz: 'Konsert', type: 'noun', article: 'das' },
  { id: 135, lesson: 7, de: 'Das Fitnessstudio', uz: 'Fitnes studiya', type: 'noun', article: 'das' },
  { id: 136, lesson: 7, de: 'lieben', uz: 'Sevmoq', type: 'verb' },
  { id: 137, lesson: 7, de: 'im Internet surfen', uz: "Internetda o'tirmoq", type: 'phrase' },
  { id: 138, lesson: 7, de: 'lange', uz: 'Uzoq', type: 'adverb' },
  { id: 139, lesson: 7, de: 'Der Ausflug', uz: 'Sayohat', type: 'noun', article: 'der' },
  { id: 140, lesson: 7, de: 'Freunde treffen', uz: "Do'stlar bilan uchrashmoq", type: 'phrase' },

  // ─── LEKTION 8: Wann? ───────────────────────────────────────────────────
  { id: 141, lesson: 8, de: 'Das Schwimmbad', uz: 'Suzish havzasi', type: 'noun', article: 'das' },
  { id: 142, lesson: 8, de: 'Das Kino', uz: 'Kinoteatr', type: 'noun', article: 'das' },
  { id: 143, lesson: 8, de: 'heute', uz: 'Bugun', type: 'adverb' },
  { id: 144, lesson: 8, de: 'Wann?', uz: 'Qachon?', type: 'other' },
  { id: 145, lesson: 8, de: 'Das Wochenende', uz: 'Dam olish kunlari', type: 'noun', article: 'das' },
  { id: 146, lesson: 8, de: 'Der Morgen', uz: 'Erta(si kun)', type: 'noun', article: 'der' },
  { id: 147, lesson: 8, de: 'Der Nachmittag', uz: "Tushlikdan so'ng", type: 'noun', article: 'der' },
  { id: 148, lesson: 8, de: 'Der Abend', uz: 'Kechqurun', type: 'noun', article: 'der' },
  { id: 149, lesson: 8, de: 'Die Nacht', uz: 'Tun', type: 'noun', article: 'die' },
  { id: 150, lesson: 8, de: 'Wie viel Uhr?', uz: 'Soat nechida?', type: 'phrase' },
  { id: 151, lesson: 8, de: 'um halb', uz: 'ga yarim soat qolganda', type: 'phrase' },
  { id: 152, lesson: 8, de: 'um viertel nach', uz: "dan 15 minut o'tganda", type: 'phrase' },
  { id: 153, lesson: 8, de: 'Der Wochentag', uz: 'Hafta kunlari', type: 'noun', article: 'der' },
  { id: 154, lesson: 8, de: 'Die Idee', uz: "G'oya", type: 'noun', article: 'die' },
  { id: 155, lesson: 8, de: 'tut mir leid', uz: 'Afsusdaman', type: 'phrase' },

  // ─── LEKTION 9: Essen & Trinken ─────────────────────────────────────────
  { id: 156, lesson: 9, de: 'mögen', uz: 'Yoqtirmoq', type: 'verb' },
  { id: 157, lesson: 9, de: 'essen', uz: 'Yemoq', type: 'verb' },
  { id: 158, lesson: 9, de: 'trinken', uz: 'Ichmoq', type: 'verb' },
  { id: 159, lesson: 9, de: 'lecker', uz: 'Mazali', type: 'adjective' },
  { id: 160, lesson: 9, de: 'Das Frühstück', uz: 'Nonushta', type: 'noun', article: 'das' },
  { id: 161, lesson: 9, de: 'Das Abendessen', uz: 'Kechki ovqat', type: 'noun', article: 'das' },
  { id: 162, lesson: 9, de: 'Das Getränk', uz: 'Ichimlik', type: 'noun', article: 'das' },
  { id: 163, lesson: 9, de: 'Die Butter', uz: "Sariyog'", type: 'noun', article: 'die' },
  { id: 164, lesson: 9, de: 'das Ei', uz: 'Tuxum', type: 'noun', article: 'das' },
  { id: 165, lesson: 9, de: 'Die Milch', uz: 'Sut', type: 'noun', article: 'die' },
  { id: 166, lesson: 9, de: 'Das Wasser', uz: 'Suv', type: 'noun', article: 'das' },
  { id: 167, lesson: 9, de: 'Der Käse', uz: "Pishloq", type: 'noun', article: 'der' },
  { id: 168, lesson: 9, de: 'Der Schinken', uz: 'Qovurdoq', type: 'noun', article: 'der' },
  { id: 169, lesson: 9, de: 'Die Speisekarte', uz: 'Menyu', type: 'noun', article: 'die' },
  { id: 170, lesson: 9, de: 'Guten Appetit', uz: 'Yoqimli ishtaha', type: 'phrase' },
  { id: 171, lesson: 9, de: 'Die Kartoffel', uz: 'Kartoshka', type: 'noun', article: 'die' },
  { id: 172, lesson: 9, de: 'Das Huhn', uz: 'Tovuq', type: 'noun', article: 'das' },
  { id: 173, lesson: 9, de: 'Der Reis', uz: 'Guruch', type: 'noun', article: 'der' },
  { id: 174, lesson: 9, de: 'Das Eis', uz: 'Muzqaymoq', type: 'noun', article: 'das' },
  { id: 175, lesson: 9, de: 'möchten', uz: 'Xohlamoq', type: 'verb' },

  // ─── LEKTION 10: Der Flughafen ──────────────────────────────────────────
  { id: 176, lesson: 10, de: 'Der Flughafen', uz: 'Aeroport', type: 'noun', article: 'der' },
  { id: 177, lesson: 10, de: 'Der Flug', uz: 'Parvoz', type: 'noun', article: 'der' },
  { id: 178, lesson: 10, de: 'Die Reise', uz: 'Sayohat', type: 'noun', article: 'die' },
  { id: 179, lesson: 10, de: 'abfliegen', uz: 'Uchib ketmoq', type: 'verb' },
  { id: 180, lesson: 10, de: 'ankommen', uz: 'Yetib kelmoq', type: 'verb' },
  { id: 181, lesson: 10, de: 'Die Verspätung', uz: 'Kechikish', type: 'noun', article: 'die' },
  { id: 182, lesson: 10, de: 'Das Gepäck', uz: 'Yuk', type: 'noun', article: 'das' },
  { id: 183, lesson: 10, de: 'einsteigen', uz: 'Chiqmoq (transportga)', type: 'verb' },
  { id: 184, lesson: 10, de: 'aussteigen', uz: 'Tushmoq (transportdan)', type: 'verb' },
  { id: 185, lesson: 10, de: 'Der Bahnsteig', uz: 'Perron', type: 'noun', article: 'der' },
  { id: 186, lesson: 10, de: 'natürlich', uz: 'Albatta', type: 'adverb' },
  { id: 187, lesson: 10, de: 'Der Hauptbahnhof', uz: 'Vokzal', type: 'noun', article: 'der' },
  { id: 188, lesson: 10, de: 'verstehen', uz: 'Tushunmoq', type: 'verb' },
  { id: 189, lesson: 10, de: 'anrufen', uz: "Qo'ngiroq qilmoq", type: 'verb' },
  { id: 190, lesson: 10, de: 'abholen', uz: 'Kutib olmoq', type: 'verb' },

  // ─── LEKTION 11: Gestern ────────────────────────────────────────────────
  { id: 191, lesson: 11, de: 'gestern', uz: 'Kecha', type: 'adverb' },
  { id: 192, lesson: 11, de: 'Der Spaziergang', uz: 'Piyoda sayohat', type: 'noun', article: 'der' },
  { id: 193, lesson: 11, de: 'Der Wald', uz: "O'rmon", type: 'noun', article: 'der' },
  { id: 194, lesson: 11, de: 'aufräumen', uz: "Yig'ishtirmoq", type: 'verb' },
  { id: 195, lesson: 11, de: 'Der Film', uz: 'Kinofilm', type: 'noun', article: 'der' },
  { id: 196, lesson: 11, de: 'Der Urlaub', uz: "Ta'til", type: 'noun', article: 'der' },
  { id: 197, lesson: 11, de: 'Die Blume', uz: 'Gul', type: 'noun', article: 'die' },
  { id: 198, lesson: 11, de: 'zurückkommen', uz: 'Qaytib kelmoq', type: 'verb' },
  { id: 199, lesson: 11, de: 'geöffnet', uz: 'Ochiq', type: 'adjective' },
  { id: 200, lesson: 11, de: 'geschlossen', uz: 'Yopiq', type: 'adjective' },

  // ─── LEKTION 12: Der Marathon ───────────────────────────────────────────
  { id: 201, lesson: 12, de: 'Der Marathon', uz: 'Marafon', type: 'noun', article: 'der' },
  { id: 202, lesson: 12, de: 'laufen', uz: 'Yugurmoq', type: 'verb' },
  { id: 203, lesson: 12, de: 'Das Wetter', uz: 'Ob-havo', type: 'noun', article: 'das' },
  { id: 204, lesson: 12, de: 'der Herbst', uz: 'Kuz', type: 'noun', article: 'der' },
  { id: 205, lesson: 12, de: 'der Winter', uz: 'Qish', type: 'noun', article: 'der' },
  { id: 206, lesson: 12, de: 'der Sommer', uz: 'Yoz', type: 'noun', article: 'der' },
  { id: 207, lesson: 12, de: 'Der Geburtstag', uz: "Tug'ilgan kun", type: 'noun', article: 'der' },
  { id: 208, lesson: 12, de: 'Die Jahreszeiten', uz: 'Yil fasllari', type: 'noun', article: 'die' },
  { id: 209, lesson: 12, de: 'Der Monat', uz: 'Oy', type: 'noun', article: 'der' },
  { id: 210, lesson: 12, de: 'wandern', uz: 'Piyoda yurmoq', type: 'verb' },
  { id: 211, lesson: 12, de: 'feiern', uz: 'Nishonlamoq', type: 'verb' },
  { id: 212, lesson: 12, de: 'Das Volksfest', uz: "Xalq sayli", type: 'noun', article: 'das' },

  // ─── LEKTION 13: Die Mauer ──────────────────────────────────────────────
  { id: 213, lesson: 13, de: 'Die Mauer', uz: 'Devor', type: 'noun', article: 'die' },
  { id: 214, lesson: 13, de: 'Die Bibliothek', uz: 'Kutubxona', type: 'noun', article: 'die' },
  { id: 215, lesson: 13, de: 'Das Boot', uz: 'Qayiq', type: 'noun', article: 'das' },
  { id: 216, lesson: 13, de: 'Die Natur', uz: 'Tabiat', type: 'noun', article: 'die' },
  { id: 217, lesson: 13, de: 'helfen', uz: 'Yordam bermoq', type: 'verb' },
  { id: 218, lesson: 13, de: 'reisen', uz: 'Sayohat qilmoq', type: 'verb' },
  { id: 219, lesson: 13, de: 'gefallen', uz: 'Yoqmoq', type: 'verb' },
  { id: 220, lesson: 13, de: 'billig', uz: 'Arzon', type: 'adjective' },
  { id: 221, lesson: 13, de: 'Das Picknick', uz: 'Piknik', type: 'noun', article: 'das' },
  { id: 222, lesson: 13, de: 'Der Zoo', uz: "Hayvonot bog'i", type: 'noun', article: 'der' },

  // ─── LEKTION 14: Der Weg ────────────────────────────────────────────────
  { id: 223, lesson: 14, de: 'Das Kaufhaus', uz: 'Savdo uyi', type: 'noun', article: 'das' },
  { id: 224, lesson: 14, de: 'nach rechts', uz: "O'ngga", type: 'phrase' },
  { id: 225, lesson: 14, de: 'nach links', uz: 'Chapga', type: 'phrase' },
  { id: 226, lesson: 14, de: 'geradeaus', uz: "To'g'riga", type: 'adverb' },
  { id: 227, lesson: 14, de: 'Die Brücke', uz: "Ko'prik", type: 'noun', article: 'die' },
  { id: 228, lesson: 14, de: 'Die Ampel', uz: 'Svetafor', type: 'noun', article: 'die' },
  { id: 229, lesson: 14, de: 'weit', uz: 'Uzoq', type: 'adjective' },
  { id: 230, lesson: 14, de: 'Der Baum', uz: 'Daraxt', type: 'noun', article: 'der' },
  { id: 231, lesson: 14, de: 'abbiegen', uz: 'Burilmoq', type: 'verb' },
  { id: 232, lesson: 14, de: 'Der Platz', uz: 'Joy', type: 'noun', article: 'der' },

  // ─── LEKTION 15: Die Wohnung ────────────────────────────────────────────
  { id: 233, lesson: 15, de: 'Die Wohngemeinschaft', uz: 'Umumiy turar joy', type: 'noun', article: 'die' },
  { id: 234, lesson: 15, de: 'gemütlich', uz: 'Qulay', type: 'adjective' },
  { id: 235, lesson: 15, de: 'Der Balkon', uz: 'Balkon', type: 'noun', article: 'der' },
  { id: 236, lesson: 15, de: 'Das Fenster', uz: 'Deraza', type: 'noun', article: 'das' },
  { id: 237, lesson: 15, de: 'Die Tür', uz: 'Eshik', type: 'noun', article: 'die' },
  { id: 238, lesson: 15, de: "Der Garten", uz: "Bog'", type: 'noun', article: 'der' },
  { id: 239, lesson: 15, de: 'Die Miete', uz: 'Ijara', type: 'noun', article: 'die' },
  { id: 240, lesson: 15, de: 'umziehen', uz: "Ko'chmoq", type: 'verb' },
  { id: 241, lesson: 15, de: 'laut', uz: 'Baland (ovoz)', type: 'adjective' },
  { id: 242, lesson: 15, de: 'bezahlen', uz: "To'lamoq", type: 'verb' },

  // ─── LEKTION 16: Der Aufzug ─────────────────────────────────────────────
  { id: 243, lesson: 16, de: 'Der Aufzug', uz: 'Lift', type: 'noun', article: 'der' },
  { id: 244, lesson: 16, de: 'nervös', uz: 'Asabiy', type: 'adjective' },
  { id: 245, lesson: 16, de: 'reparieren', uz: 'Tuzatmoq', type: 'verb' },
  { id: 246, lesson: 16, de: 'pünktlich', uz: "O'z vaqtida", type: 'adjective' },
  { id: 247, lesson: 16, de: 'vereinbaren', uz: 'Kelishmoq', type: 'verb' },
  { id: 248, lesson: 16, de: 'Die Angst', uz: "Qo'rquv", type: 'noun', article: 'die' },
  { id: 249, lesson: 16, de: 'funktionieren', uz: 'Ishlamoq', type: 'verb' },
  { id: 250, lesson: 16, de: 'erklären', uz: 'Tushuntirmoq', type: 'verb' },

  // ─── LEKTION 17: Träume ─────────────────────────────────────────────────
  { id: 251, lesson: 17, de: 'werden', uz: "Bo'lmoq", type: 'verb' },
  { id: 252, lesson: 17, de: 'wollen', uz: 'Xohlamoq', type: 'verb' },
  { id: 253, lesson: 17, de: 'Das Geld', uz: 'Pul', type: 'noun', article: 'das' },
  { id: 254, lesson: 17, de: 'Die Welt', uz: 'Dunyo', type: 'noun', article: 'die' },
  { id: 255, lesson: 17, de: 'wichtig', uz: 'Muhim', type: 'adjective' },
  { id: 256, lesson: 17, de: 'heiraten', uz: 'Turmush qurmoq', type: 'verb' },
  { id: 257, lesson: 17, de: 'auf jeden Fall', uz: 'Har qanday holatda', type: 'phrase' },
  { id: 258, lesson: 17, de: 'auf keinen Fall', uz: 'Hech qachon', type: 'phrase' },
  { id: 259, lesson: 17, de: 'Der Berg', uz: "Tog'", type: 'noun', article: 'der' },
  { id: 260, lesson: 17, de: 'Das Ausland', uz: 'Chet el', type: 'noun', article: 'das' },

  // ─── LEKTION 18: Gesundheit ─────────────────────────────────────────────
  { id: 261, lesson: 18, de: 'Der Kopf', uz: 'Bosh', type: 'noun', article: 'der' },
  { id: 262, lesson: 18, de: 'Der Schmerz', uz: "Og'riq", type: 'noun', article: 'der' },
  { id: 263, lesson: 18, de: 'müde', uz: 'Charchagan', type: 'adjective' },
  { id: 264, lesson: 18, de: 'krank', uz: 'Kasal', type: 'adjective' },
  { id: 265, lesson: 18, de: 'gesund', uz: "Sog'lom", type: 'adjective' },
  { id: 266, lesson: 18, de: 'Das Fieber', uz: 'Isitma', type: 'noun', article: 'das' },
  { id: 267, lesson: 18, de: 'Die Erkältung', uz: 'Shamollash', type: 'noun', article: 'die' },
  { id: 268, lesson: 18, de: 'Der Honig', uz: 'Asal', type: 'noun', article: 'der' },
  { id: 269, lesson: 18, de: 'sollen', uz: 'Shart, lozim', type: 'verb' },
  { id: 270, lesson: 18, de: 'Die Tablette', uz: 'Tabletka', type: 'noun', article: 'die' },
  { id: 271, lesson: 18, de: 'Das Medikament', uz: 'Dori vositalari', type: 'noun', article: 'das' },
  { id: 272, lesson: 18, de: 'wehtun', uz: "Og'rimoq", type: 'verb' },

  // ─── LEKTION 19: Haushalt ───────────────────────────────────────────────
  { id: 273, lesson: 19, de: 'aufmachen', uz: 'Ochmoq', type: 'verb' },
  { id: 274, lesson: 19, de: 'zumachen', uz: 'Yopmoq', type: 'verb' },
  { id: 275, lesson: 19, de: 'Der Abfall', uz: 'Chiqindi', type: 'noun', article: 'der' },
  { id: 276, lesson: 19, de: 'sauber', uz: 'Toza', type: 'adjective' },
  { id: 277, lesson: 19, de: 'schmutzig', uz: 'Iflos', type: 'adjective' },
  { id: 278, lesson: 19, de: 'vergessen', uz: 'Unutmoq', type: 'verb' },
  { id: 279, lesson: 19, de: 'lachen', uz: 'Kulmoq', type: 'verb' },
  { id: 280, lesson: 19, de: 'rauchen', uz: 'Chekmoq', type: 'verb' },
  { id: 281, lesson: 19, de: 'putzen', uz: 'Tozalamoq', type: 'verb' },
  { id: 282, lesson: 19, de: 'Das Geschirr', uz: 'Idish tovoq', type: 'noun', article: 'das' },

  // ─── LEKTION 20: Das Team ───────────────────────────────────────────────
  { id: 283, lesson: 20, de: 'Der Fehler', uz: 'Xato', type: 'noun', article: 'der' },
  { id: 284, lesson: 20, de: 'freundlich', uz: "Do'stona", type: 'adjective' },
  { id: 285, lesson: 20, de: 'kreativ', uz: 'Kreativ', type: 'adjective' },
  { id: 286, lesson: 20, de: 'erfolgreich', uz: 'Muvaffaqiyatli', type: 'adjective' },
  { id: 287, lesson: 20, de: 'sympathisch', uz: 'Yoqimli', type: 'adjective' },
  { id: 288, lesson: 20, de: 'fröhlich', uz: 'Quvnoq', type: 'adjective' },
  { id: 289, lesson: 20, de: 'ruhig', uz: 'Sokin, tinch', type: 'adjective' },
  { id: 290, lesson: 20, de: 'langweilig', uz: 'Zerikarli', type: 'adjective' },

  // ─── LEKTION 21: Verboten! ──────────────────────────────────────────────
  { id: 291, lesson: 21, de: 'verboten', uz: 'Taqiqlangan', type: 'adjective' },
  { id: 292, lesson: 21, de: 'erlaubt', uz: 'Ruxsat berilgan', type: 'adjective' },
  { id: 293, lesson: 21, de: 'gefährlich', uz: 'Xavfli', type: 'adjective' },
  { id: 294, lesson: 21, de: 'Die Umwelt', uz: 'Atrof-muhit', type: 'noun', article: 'die' },
  { id: 295, lesson: 21, de: 'Der Nachbar', uz: "Qo'shni", type: 'noun', article: 'der' },
  { id: 296, lesson: 21, de: 'gemeinsam', uz: 'Birgalikda', type: 'adverb' },
  { id: 297, lesson: 21, de: 'dürfen', uz: 'Ruxsat bo\'lmoq', type: 'verb' },
  { id: 298, lesson: 21, de: 'müssen', uz: 'Kerak, lozim', type: 'verb' },
  { id: 299, lesson: 21, de: 'Das Gemüse', uz: 'Sabzavotlar', type: 'noun', article: 'das' },
  { id: 300, lesson: 21, de: 'zelten', uz: 'Chodir tikmoq', type: 'verb' },

  // ─── LEKTION 22: Kleidung ───────────────────────────────────────────────
  { id: 301, lesson: 22, de: 'Die Kleidung', uz: 'Kiyim', type: 'noun', article: 'die' },
  { id: 302, lesson: 22, de: 'Die Jeans', uz: 'Jensi', type: 'noun', article: 'die' },
  { id: 303, lesson: 22, de: 'anziehen', uz: 'Kiyinmoq', type: 'verb' },
  { id: 304, lesson: 22, de: 'Die Qualität', uz: 'Sifat', type: 'noun', article: 'die' },
  { id: 305, lesson: 22, de: 'tauschen', uz: 'Almashmoq', type: 'verb' },
  { id: 306, lesson: 22, de: 'nähen', uz: 'Tikmoq', type: 'verb' },
  { id: 307, lesson: 22, de: 'am liebsten', uz: 'Eng sevimli', type: 'phrase' },
  { id: 308, lesson: 22, de: 'verschieden', uz: 'Turli xil', type: 'adjective' },

  // ─── LEKTION 23: Gefühle ────────────────────────────────────────────────
  { id: 309, lesson: 23, de: 'glücklich', uz: 'Baxtli', type: 'adjective' },
  { id: 310, lesson: 23, de: 'Die Heimat', uz: 'Vatan', type: 'noun', article: 'die' },
  { id: 311, lesson: 23, de: 'Das Meer', uz: 'Dengiz', type: 'noun', article: 'das' },
  { id: 312, lesson: 23, de: 'einsam', uz: "Yolg'iz", type: 'adjective' },
  { id: 313, lesson: 23, de: 'Das Zelt', uz: 'Chodir', type: 'noun', article: 'das' },
  { id: 314, lesson: 23, de: 'Das Kamel', uz: 'Tuya', type: 'noun', article: 'das' },
  { id: 315, lesson: 23, de: 'stark', uz: 'Kuchli', type: 'adjective' },
  { id: 316, lesson: 23, de: 'warum?', uz: 'Nima uchun?', type: 'other' },

  // ─── LEKTION 24: Feiertage ──────────────────────────────────────────────
  { id: 317, lesson: 24, de: 'Die Hochzeit', uz: "To'y", type: 'noun', article: 'die' },
  { id: 318, lesson: 24, de: 'gratulieren', uz: 'Tabriklamoq', type: 'verb' },
  { id: 319, lesson: 24, de: 'Die Prüfung', uz: 'Imtihon', type: 'noun', article: 'die' },
  { id: 320, lesson: 24, de: 'wunderbar', uz: 'Ajoyib', type: 'adjective' },
  { id: 321, lesson: 24, de: 'stattfinden', uz: "Bo'lib o'tmoq", type: 'verb' },
  { id: 322, lesson: 24, de: 'Die Freude', uz: 'Quvonch', type: 'noun', article: 'die' },
  { id: 323, lesson: 24, de: 'Das Neujahr', uz: 'Yangi yil', type: 'noun', article: 'das' },
  { id: 324, lesson: 24, de: 'Der Glückwunsch', uz: 'Tabrik', type: 'noun', article: 'der' },
  { id: 325, lesson: 24, de: 'alles Gute', uz: 'Barcha yaxshiliklar', type: 'phrase' },
  { id: 326, lesson: 24, de: 'Die Liebe', uz: 'Sevgi', type: 'noun', article: 'die' },
];

export const LESSONS_META = [
  { id: 1,  title_de: 'Wie heißt du?',   title_uz: 'Isming nima?',        module: 1 },
  { id: 2,  title_de: 'Jahre alt',        title_uz: 'Yosh',                module: 1 },
  { id: 3,  title_de: 'Die Familie',      title_uz: 'Oila',                module: 1 },
  { id: 4,  title_de: 'Zu Hause',         title_uz: 'Uyda',                module: 1 },
  { id: 5,  title_de: 'Das Ding',         title_uz: 'Narsalar',            module: 2 },
  { id: 6,  title_de: 'Oh Gott!',         title_uz: 'Kundalik hayot',      module: 2 },
  { id: 7,  title_de: 'Hobbys',           title_uz: 'Qiziqishlar',         module: 2 },
  { id: 8,  title_de: 'Wann?',            title_uz: 'Qachon?',             module: 2 },
  { id: 9,  title_de: 'Essen & Trinken',  title_uz: 'Ovqat va ichimlik',  module: 3 },
  { id: 10, title_de: 'Der Flughafen',    title_uz: 'Aeroport',            module: 3 },
  { id: 11, title_de: 'Gestern',          title_uz: 'Kecha',               module: 3 },
  { id: 12, title_de: 'Der Marathon',     title_uz: 'Marafon',             module: 3 },
  { id: 13, title_de: 'Die Mauer',        title_uz: 'Devor',               module: 4 },
  { id: 14, title_de: 'Der Weg',          title_uz: "Yo'l",                module: 4 },
  { id: 15, title_de: 'Die Wohnung',      title_uz: 'Uy-joy',              module: 4 },
  { id: 16, title_de: 'Der Aufzug',       title_uz: 'Lift',                module: 4 },
  { id: 17, title_de: 'Träume',           title_uz: 'Orzular',             module: 5 },
  { id: 18, title_de: 'Gesundheit',       title_uz: 'Salomatlik',          module: 5 },
  { id: 19, title_de: 'Haushalt',         title_uz: 'Uy ishlari',          module: 5 },
  { id: 20, title_de: 'Das Team',         title_uz: 'Jamoa',               module: 5 },
  { id: 21, title_de: 'Verboten!',        title_uz: 'Taqiq',               module: 6 },
  { id: 22, title_de: 'Kleidung',         title_uz: 'Kiyim',               module: 6 },
  { id: 23, title_de: 'Gefühle',          title_uz: "His-tuyg'ular",       module: 6 },
  { id: 24, title_de: 'Feiertage',        title_uz: 'Bayramlar',           module: 6 },
];
